# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random

### Assignment 1: Array Creation and Manipulation


#### 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [16]:
import random
arr = np.array([random.randint(1,20) for _ in range(1,26)]).reshape(5,5)
arr[:,2:3] = 1
arr

array([[18, 11,  1, 13, 15],
       [10, 15,  1, 14,  8],
       [14, 16,  1, 13,  5],
       [10, 14,  1, 16,  5],
       [ 2, 15,  1, 14, 18]])

#### 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [21]:
arr = np.arange(1,17,1).reshape(4,4)
np.fill_diagonal(arr,0)
arr

array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])

### Assignment 2: Array Indexing and Slicing

#### 1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [27]:
arr = np.arange(1,37,1).reshape(6,6)
print(arr)
print(arr[2:5,1:4])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[14 15 16]
 [20 21 22]
 [26 27 28]]


#### 2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [36]:
nums = np.array([random.randint(1,25) for _ in range(1,26)]).reshape(5,5)
print(nums)
print("upper")
print(nums[0:1,:])
print("right")
print(nums[:,4:])
print("lower")
print(nums[4:,:])
print("left")
print(nums[:,0:1])

[[13 10  9  2 12]
 [14 23 16 20  3]
 [21  8 15  2 17]
 [21 22 17 17 13]
 [19 22  4 21  1]]
upper
[[13 10  9  2 12]]
right
[[12]
 [ 3]
 [17]
 [13]
 [ 1]]
lower
[[19 22  4 21  1]]
left
[[13]
 [14]
 [21]
 [21]
 [19]]


### Assignment 3: Array Operations

#### 1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [63]:
arr1 = np.random.randint(1,13,size = (3,4))
arr2 = np.random.randint(1,13, size = (3,4))
print(arr1+arr2)
print()
print(arr1-arr2)
print()
print(arr1*arr2)
print()
print(arr1/arr2)

[[14 14 17 17]
 [10  8 10 15]
 [ 9 13 12 11]]

[[ 8 -4  1  5]
 [ 6 -6  6 -5]
 [-3  1  2  7]]

[[33 45 72 66]
 [16  7 16 50]
 [18 42 35 18]]

[[3.66666667 0.55555556 1.125      1.83333333]
 [4.         0.14285714 4.         0.5       ]
 [0.5        1.16666667 1.4        4.5       ]]


#### 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [68]:
arr = np.random.randint(1,17,size=(4,4))
row_sum = np.sum(arr, axis = 1)
col_sum = np.sum(arr,axis = 0)
print(row_sum)
print(col_sum)

[24 17 23 33]
[17 31 17 32]


### Assignment 4: Statistical Operations

#### 1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [78]:
array = np.array([random.randint(1,25) for _ in range(0,25)]).reshape(5,5)
print(np.mean(array))
print(np.median(array))
print(np.std(array))
print(np.var(array))

12.96
12.0
6.095769024495596
37.1584


#### 2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [79]:
data = np.arange(1,10,1).reshape(3,3)
normalized_data = (data-np.mean(data))/np.std(data)
print(normalized_data)

[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

#### 1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [3]:
arr = np.random.randint(1,10,size=(3,3))
arr2 = np.array([1,2,3])
print(arr)
print()
print(arr2+arr)

[[8 5 6]
 [4 6 3]
 [3 3 7]]

[[ 9  7  9]
 [ 5  8  6]
 [ 4  5 10]]


: 

#### 2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [19]:
arr1 = np.array([random.randint(1,10) for _ in range(16)]).reshape(4,4)
print("Array1",arr1)
arr2 = np.array([random.randint(1,20) for _ in range(4)])
print("Array2",arr2)
result = arr1-arr2[:,np.newaxis]
print(result)

Array1 [[ 1  3  1  1]
 [ 4  5  4 10]
 [ 2  1  2  9]
 [ 5  7  9 10]]
Array2 [16  3 19  5]
[[-15 -13 -15 -15]
 [  1   2   1   7]
 [-17 -18 -17 -10]
 [  0   2   4   5]]


### Assignment 6: Linear Algebra

#### 1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [26]:
A = np.array([random.randint(1,10) for _ in range(1,10)]).reshape(3,3)
# print(A)
determinant = np.linalg.det(A)
inverse = np.linalg.inv(A)
eigenvalues = np.linalg.eigvals(A)
print(determinant,'\n', inverse,'\n', eigenvalues)

389.99999999999966 
 [[ 0.02564103  0.14102564 -0.1025641 ]
 [-0.09230769 -0.00769231  0.16923077]
 [ 0.17435897 -0.04102564 -0.0974359 ]] 
 [17.13695401+0.j         -1.56847701+4.50529872j -1.56847701-4.50529872j]


#### 2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [28]:
arr1 = np.random.randint(1,10, size=(3,2))
arr2 = np.random.randint(1,10, size=(2,3))
result = np.dot(arr1,arr2)
print(result)

[[ 80 136  24]
 [ 20  57   8]
 [ 62  87  17]]


### Assignment 7 : Advanced Array Manipulation

#### 1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [3]:
arr = np.array([i for i in range(1,10)]).reshape(3,3)
print("Original Array : ")
print(arr)
print("Flattened array : ")
print(arr.reshape(1,9))
print("Reshaped Array : ")
print(arr.reshape(9,1))

Original Array : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened array : 
[[1 2 3 4 5 6 7 8 9]]
Reshaped Array : 
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


#### 2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [7]:
arr = np.random.randint(1,25,size=(5,5))
print("Original Array : ")
print(arr)
flattened_array = arr.flatten()
print("Falttend array")
print(flattened_array)
print(flattened_array.reshape(5,5))


Original Array : 
[[ 6  1 20  3  4]
 [24  8 18  4  9]
 [13 16 17 19 15]
 [ 4  2 20 23  1]
 [ 9  4  3 21 19]]
Falttend array
[ 6  1 20  3  4 24  8 18  4  9 13 16 17 19 15  4  2 20 23  1  9  4  3 21
 19]
[[ 6  1 20  3  4]
 [24  8 18  4  9]
 [13 16 17 19 15]
 [ 4  2 20 23  1]
 [ 9  4  3 21 19]]


### Assignment 8: Fancy Indexing and Boolean Indexing

#### 1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [14]:
arr = np.random.randint(1,25,size=(5,5))
indices = [0,0,-1,-1],[0,-1,0,-1]
print(arr)
print(arr[([0,0,-1,-1],[0,-1,0,-1])])

[[ 8  7 18  6 13]
 [ 5 10  8 23 22]
 [ 5 14  2  5 21]
 [11  5 11 21  4]
 [24 10 23  3  2]]
[ 8 13 24  2]


#### 2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [16]:
arr = np.random.randint(1,16,size=(4,4))
print("Original Array")
print(arr)
arr[arr>10] = 10
print("Modified array : ")
print(arr)

Original Array
[[14  6  4  2]
 [ 2  5  9  8]
 [ 1  2  8 11]
 [ 2  5 10  6]]
Modified array : 
[[10  6  4  2]
 [ 2  5  9  8]
 [ 1  2  8 10]
 [ 2  5 10  6]]


### Assignment 9: Structured Arrays

#### 1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [19]:
data_type = [("name","U20"),("age","i8"),("weight","f8")]
data = np.array([("Danny Whiz-Bang",30,81.5),("Freddie Thorne",26,72.8),("Thomas Shelby",25,69.8)],dtype=data_type)
sorted_data = np.sort(data, order="age")
print(sorted_data)

[('Thomas Shelby', 25, 69.8) ('Freddie Thorne', 26, 72.8)
 ('Danny Whiz-Bang', 30, 81.5)]


#### 2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [21]:
data_type = [("x","i2"),("y","i2")]
data = np.array([(2,5),(4,6),(3,8)],dtype=data_type)
euclidean_distance = np.sqrt((data['x']-data['x'][:,np.newaxis])**2 + (data['y'][:,np.newaxis]-data['y'])**2)
print(euclidean_distance)

[[0.        2.236068  3.1622777]
 [2.236068  0.        2.236068 ]
 [3.1622777 2.236068  0.       ]]


### Assignment 10: Masked Arrays


#### 1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [22]:
import numpy.ma as ma
arr = np.random.randint(1,16,size=(4,4))
print("arr : ")
print(arr)
arr_masked = ma.masked_greater(arr,10)
print("arr_masked : ")
print(arr_masked)
sum_masked = arr_masked.sum()
print(sum_masked)


arr : 
[[11  7  1 14]
 [ 8  8  3  5]
 [12  9 10  2]
 [ 6  9  6  3]]
arr_masked : 
[[-- 7 1 --]
 [8 8 3 5]
 [-- 9 10 2]
 [6 9 6 3]]
77


#### 2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [26]:
arr = np.random.randint(1,10,size=(3,3))
print("Original array : ")
print(arr)
masked_arr = ma.masked_array(arr, np.eye(3,dtype=bool))
print("Masked Array : ")
print(masked_arr)

unmasked_mean = masked_arr.mean()
updated_masked = masked_arr.filled(unmasked_mean)
print("Updated Masked Array : ")
print(updated_masked)

Original array : 
[[8 1 1]
 [1 9 3]
 [4 1 8]]
Masked Array : 
[[-- 1 1]
 [1 -- 3]
 [4 1 --]]
Updated Masked Array : 
[[1 1 1]
 [1 1 3]
 [4 1 1]]
