In [4]:
import numpy as np
arr1 = np.array([1,2,3,4,5,6])
arr1
print(type(arr1))
print(arr1.shape)

<class 'numpy.ndarray'>
(6,)


In [11]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)
arr2.reshape(2,4)

ValueError: cannot reshape array of size 5 into shape (2,4)

In [12]:
arr3 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
arr3

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [15]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [27]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
np.eye(1)

array([[1.]])

In [34]:
arr1.itemsize

8

In [42]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])
print(arr1+arr2)
print(arr1-arr2)
print(np.sqrt(arr1))
print(np.exp(arr2))
print(np.sin(arr1))

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[1.         1.41421356 1.73205081 2.         2.23606798]
[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
